name: Build
on:
  push:

env:
  USERNAME: kwsp
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/kwsp/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/kwsp/index.json,readwrite"

jobs:
  Build-Win64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup VCPKG
        shell: pwsh
        run: |
          cd ${{ github.workspace }}
          git clone https://github.com/microsoft/vcpkg
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat

      - name: Add NuGet sources
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GH_PACKAGES_TOKEN }}"
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: CMake configure
        shell: pwsh
        run: cmake --preset win64

      - name: CMake build
        shell: pwsh
        run: cmake --build --preset win64-release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ github.workspace }}/build/win64/src/Release/main.exe
          if-no-files-found: "warn" # output a warning if no files are found.

